version: 2.1
jobs:
  tests:
    machine:
      enabled: true
      docker_layer_caching: true
    working_directory: ~
    steps:
      - checkout
      - run:
          name: Test| check env
          command: |
            env
            echo "fim env"
            hostname
            pwd
            ls -la
      - run:
          name: Test | Build and run image
          command: |
            docker build -t mmoras/stg:my-python-app .
            docker run -it --name stg_test -p 5000:5000 -d mmoras/stg:my-python-app
      - run:
          name: Test | run env
          command: |
            docker exec -ti stg_test env

workflows:
  version: 2.1
  Workflow_TESTES:
    jobs:
      - tests:
          filters:
             branches:
                ignore: staging
  Workflow_Build:
    jobs:
      - tests:
          context: docker-repository
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^stg-\d{8}.\d{2}$/
#      - build-push:
#          context: docker-repository
#          requires:
#            - tests
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only:
#                - /^prod-\d{8}.\d{2}$/
#      - hold:
#          type: approval
#          requires:
#            - build-push
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only:
#                - /^prod-\d{8}.\d{2}$/
#      - deploy:
#          context: docker-repository
#          requires:
#            - hold
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only:
#                - /^prod-\d{8}.\d{2}$/
