version: 2.1
jobs:
  tests:
    machine:
      enabled: true
      docker_layer_caching: true
    working_directory: ~
    steps:
      - checkout
      - run:
          name: Test| check env
          command: |
            mkdir test
            env
            set
            hostname
            pwd
            ls -la

workflows:
  version: 2.1
  tests:
    jobs:
      - tests:
          filters:
             branches:
                ignore: staging
