version: 2.1
jobs:
  tests:
    machine:
      enabled: true
      docker_layer_caching: true
    working_directory: ~
    steps:
      - checkout
      - run:
          name: Test| check env
          command: |
            env
            echo "fim env"
            hostname
            pwd
            ls -la
      - run:
          name: Test | Build and run image
          command: |
            docker build -t mmoras/stg:test .
            docker run -it --name stg_test -d mmoras/stg:test
      - run:
          name: Test | run env
          command: |
            docker exec -ti stg_test env

workflows:
  version: 2.1
  WorkflowName:
    jobs:
      - tests:
          filters:
             branches:
                ignore: master
