version: 2
jobs:
  tests:
    machine:
      enabled: true
      docker_layer_caching: true
    working_directory: ~
    steps:
      - checkout
      - run:
          name: Test| check env
          command: |
            env
            echo "fim env"
            hostname
            pwd
            ls -la
      - run:
          name: Test | Build and run image
          command: |
            docker build -t mmoras/stg:my-python-app .
            docker run -it --name stg_test -p 5000:5000 -d mmoras/stg:my-python-app
      - run:
          name: Test | run env
          command: |
            docker exec -ti stg_test env
  build-push:
    machine:
      enabled: true
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t mmoras/app:$CIRCLE_TAG .
      - run:
          name: Push Docker image to Registry
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
             
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
                 
                DOCKER_IMAGE="mmoras/app:${CIRCLE_TAG}"
 
                if [[ "$CIRCLE_TAG" =~ ^prod ]]; then
                  docker tag $DOCKER_IMAGE 'mmoras/app:latest'
                  docker push 'mmoras/app:latest'
                elif [[ "$CIRCLE_TAG" =~ ^stg ]]; then
                  docker tag $DOCKER_IMAGE 'mmoras/app:stg-latest'
                  docker push 'mmoras/app::stg-latest'
                fi
                 
                docker push $DOCKER_IMAGE
                exit 0
            fi
workflows:
  version: 2
  WorkflowBuild:
    jobs:
      - tests:
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^stg-\d{8}.\d{2}$/
      - build-push:
          context: docker-repository
          requires:
            - tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^stg-\d{8}.\d{2}$/
